export interface RosarySchedule {
  person: string;
  weeks: string[];
}

export const weekDates = [
  { start: "2025-09-28", end: "2025-10-04", week: 0 },
  { start: "2025-10-05", end: "2025-10-11", week: 1 },
  { start: "2025-10-12", end: "2025-10-18", week: 2 },
  { start: "2025-10-19", end: "2025-10-25", week: 3 },
  { start: "2025-10-26", end: "2025-11-01", week: 4 },
  { start: "2025-11-02", end: "2025-11-08", week: 5 },
  { start: "2025-11-09", end: "2025-11-15", week: 6 },
  { start: "2025-11-16", end: "2025-11-22", week: 7 },
  { start: "2025-11-23", end: "2025-11-29", week: 8 },
  { start: "2025-11-30", end: "2025-12-06", week: 9 },
  { start: "2025-12-07", end: "2025-12-13", week: 10 },
  { start: "2025-12-14", end: "2025-12-20", week: 11 },
  { start: "2025-12-21", end: "2025-12-27", week: 12 },
  { start: "2025-12-28", end: "2026-01-03", week: 13 },
  { start: "2026-01-04", end: "2026-01-10", week: 14 },
  { start: "2026-01-11", end: "2026-01-17", week: 15 },
  { start: "2026-01-18", end: "2026-01-24", week: 16 },
  { start: "2026-01-25", end: "2026-01-31", week: 17 },
  { start: "2026-02-01", end: "2026-02-07", week: 18 },
  { start: "2026-02-08", end: "2026-02-14", week: 19 },
  { start: "2026-02-15", end: "2026-02-21", week: 20 },
];

export const rosarySchedule: RosarySchedule[] = [
  {
    person: "Alek F.",
    weeks: [
      "Zwiastowanie",
      "Nawiedzenie",
      "Narodzenie",
      "Ofiarowanie",
      "Znalezienie",
      "Chrzest w Jordanie",
      "Cud w Kanie",
      "Głoszenie Królestwa Bożego",
      "Przemienienie na górze Tabor",
      "Ustanowienie Eucharystii",
      "Modlitwa w Ogrójcu",
      "Biczowanie",
      "Cierniem ukoronowanie",
      "Droga Krzyżowa",
      "Ukrzyżowanie i śmierć",
      "Zmartwychwstanie",
      "Wniebowstąpienie",
      "Zesłanie Ducha Świętego",
      "Wniebowzięcie NMP",
      "Ukoronowanie NMP",
    ],
  },
  {
    person: "Aneta P.",
    weeks: [
      "Nawiedzenie",
      "Narodzenie",
      "Ofiarowanie",
      "Znalezienie",
      "Chrzest w Jordanie",
      "Cud w Kanie",
      "Głoszenie Królestwa Bożego",
      "Przemienienie na górze Tabor",
      "Ustanowienie Eucharystii",
      "Modlitwa w Ogrójcu",
      "Biczowanie",
      "Cierniem ukoronowanie",
      "Droga Krzyżowa",
      "Ukrzyżowanie i śmierć",
      "Zmartwychwstanie",
      "Wniebowstąpienie",
      "Zesłanie Ducha Świętego",
      "Wniebowzięcie NMP",
      "Ukoronowanie NMP",
      "Zwiastowanie",
    ],
  },
  {
    person: "Beata D.",
    weeks: [
      "Narodzenie",
      "Ofiarowanie",
      "Znalezienie",
      "Chrzest w Jordanie",
      "Cud w Kanie",
      "Głoszenie Królestwa Bożego",
      "Przemienienie na górze Tabor",
      "Ustanowienie Eucharystii",
      "Modlitwa w Ogrójcu",
      "Biczowanie",
      "Cierniem ukoronowanie",
      "Droga Krzyżowa",
      "Ukrzyżowanie i śmierć",
      "Zmartwychwstanie",
      "Wniebowstąpienie",
      "Zesłanie Ducha Świętego",
      "Wniebowzięcie NMP",
      "Ukoronowanie NMP",
      "Zwiastowanie",
      "Nawiedzenie",
    ],
  },
  {
    person: "Dominik F.",
    weeks: [
      "Ofiarowanie",
      "Znalezienie",
      "Chrzest w Jordanie",
      "Cud w Kanie",
      "Głoszenie Królestwa Bożego",
      "Przemienienie na górze Tabor",
      "Ustanowienie Eucharystii",
      "Modlitwa w Ogrójcu",
      "Biczowanie",
      "Cierniem ukoronowanie",
      "Droga Krzyżowa",
      "Ukrzyżowanie i śmierć",
      "Zmartwychwstanie",
      "Wniebowstąpienie",
      "Zesłanie Ducha Świętego",
      "Wniebowzięcie NMP",
      "Ukoronowanie NMP",
      "Zwiastowanie",
      "Nawiedzenie",
      "Narodzenie",
    ],
  },
  {
    person: "Dominik J.",
    weeks: [
      "Znalezienie",
      "Chrzest w Jordanie",
      "Cud w Kanie",
      "Głoszenie Królestwa Bożego",
      "Przemienienie na górze Tabor",
      "Ustanowienie Eucharystii",
      "Modlitwa w Ogrójcu",
      "Biczowanie",
      "Cierniem ukoronowanie",
      "Droga Krzyżowa",
      "Ukrzyżowanie i śmierć",
      "Zmartwychwstanie",
      "Wniebowstąpienie",
      "Zesłanie Ducha Świętego",
      "Wniebowzięcie NMP",
      "Ukoronowanie NMP",
      "Zwiastowanie",
      "Nawiedzenie",
      "Narodzenie",
      "Ofiarowanie",
    ],
  },
  {
    person: "Dorota F.",
    weeks: [
      "Chrzest w Jordanie",
      "Cud w Kanie",
      "Głoszenie Królestwa Bożego",
      "Przemienienie na górze Tabor",
      "Ustanowienie Eucharystii",
      "Modlitwa w Ogrójcu",
      "Biczowanie",
      "Cierniem ukoronowanie",
      "Droga Krzyżowa",
      "Ukrzyżowanie i śmierć",
      "Zmartwychwstanie",
      "Wniebowstąpienie",
      "Zesłanie Ducha Świętego",
      "Wniebowzięcie NMP",
      "Ukoronowanie NMP",
      "Zwiastowanie",
      "Nawiedzenie",
      "Narodzenie",
      "Ofiarowanie",
      "Znalezienie",
    ],
  },
  {
    person: "Hubert F.",
    weeks: [
      "Cud w Kanie",
      "Głoszenie Królestwa Bożego",
      "Przemienienie na górze Tabor",
      "Ustanowienie Eucharystii",
      "Modlitwa w Ogrójcu",
      "Biczowanie",
      "Cierniem ukoronowanie",
      "Droga Krzyżowa",
      "Ukrzyżowanie i śmierć",
      "Zmartwychwstanie",
      "Wniebowstąpienie",
      "Zesłanie Ducha Świętego",
      "Wniebowzięcie NMP",
      "Ukoronowanie NMP",
      "Zwiastowanie",
      "Nawiedzenie",
      "Narodzenie",
      "Ofiarowanie",
      "Znalezienie",
      "Chrzest w Jordanie",
    ],
  },
  {
    person: "Jadzia F.",
    weeks: [
      "Głoszenie Królestwa Bożego",
      "Przemienienie na górze Tabor",
      "Ustanowienie Eucharystii",
      "Modlitwa w Ogrójcu",
      "Biczowanie",
      "Cierniem ukoronowanie",
      "Droga Krzyżowa",
      "Ukrzyżowanie i śmierć",
      "Zmartwychwstanie",
      "Wniebowstąpienie",
      "Zesłanie Ducha Świętego",
      "Wniebowzięcie NMP",
      "Ukoronowanie NMP",
      "Zwiastowanie",
      "Nawiedzenie",
      "Narodzenie",
      "Ofiarowanie",
      "Znalezienie",
      "Chrzest w Jordanie",
      "Cud w Kanie",
    ],
  },
  {
    person: "Janusz G.",
    weeks: [
      "Przemienienie na górze Tabor",
      "Ustanowienie Eucharystii",
      "Modlitwa w Ogrójcu",
      "Biczowanie",
      "Cierniem ukoronowanie",
      "Droga Krzyżowa",
      "Ukrzyżowanie i śmierć",
      "Zmartwychwstanie",
      "Wniebowstąpienie",
      "Zesłanie Ducha Świętego",
      "Wniebowzięcie NMP",
      "Ukoronowanie NMP",
      "Zwiastowanie",
      "Nawiedzenie",
      "Narodzenie",
      "Ofiarowanie",
      "Znalezienie",
      "Chrzest w Jordanie",
      "Cud w Kanie",
      "Głoszenie Królestwa Bożego",
    ],
  },
  {
    person: "Jolanta N.",
    weeks: [
      "Ustanowienie Eucharystii",
      "Modlitwa w Ogrójcu",
      "Biczowanie",
      "Cierniem ukoronowanie",
      "Droga Krzyżowa",
      "Ukrzyżowanie i śmierć",
      "Zmartwychwstanie",
      "Wniebowstąpienie",
      "Zesłanie Ducha Świętego",
      "Wniebowzięcie NMP",
      "Ukoronowanie NMP",
      "Zwiastowanie",
      "Nawiedzenie",
      "Narodzenie",
      "Ofiarowanie",
      "Znalezienie",
      "Chrzest w Jordanie",
      "Cud w Kanie",
      "Głoszenie Królestwa Bożego",
      "Przemienienie na górze Tabor",
    ],
  },
  {
    person: "Krysia F.",
    weeks: [
      "Modlitwa w Ogrójcu",
      "Biczowanie",
      "Cierniem ukoronowanie",
      "Droga Krzyżowa",
      "Ukrzyżowanie i śmierć",
      "Zmartwychwstanie",
      "Wniebowstąpienie",
      "Zesłanie Ducha Świętego",
      "Wniebowzięcie NMP",
      "Ukoronowanie NMP",
      "Zwiastowanie",
      "Nawiedzenie",
      "Narodzenie",
      "Ofiarowanie",
      "Znalezienie",
      "Chrzest w Jordanie",
      "Cud w Kanie",
      "Głoszenie Królestwa Bożego",
      "Przemienienie na górze Tabor",
      "Ustanowienie Eucharystii",
    ],
  },
  {
    person: "Mania i Tosia F.",
    weeks: [
      "Biczowanie",
      "Cierniem ukoronowanie",
      "Droga Krzyżowa",
      "Ukrzyżowanie i śmierć",
      "Zmartwychwstanie",
      "Wniebowstąpienie",
      "Zesłanie Ducha Świętego",
      "Wniebowzięcie NMP",
      "Ukoronowanie NMP",
      "Zwiastowanie",
      "Nawiedzenie",
      "Narodzenie",
      "Ofiarowanie",
      "Znalezienie",
      "Chrzest w Jordanie",
      "Cud w Kanie",
      "Głoszenie Królestwa Bożego",
      "Przemienienie na górze Tabor",
      "Ustanowienie Eucharystii",
      "Modlitwa w Ogrójcu",
    ],
  },
  {
    person: "Mateusz F.",
    weeks: [
      "Cierniem ukoronowanie",
      "Droga Krzyżowa",
      "Ukrzyżowanie i śmierć",
      "Zmartwychwstanie",
      "Wniebowstąpienie",
      "Zesłanie Ducha Świętego",
      "Wniebowzięcie NMP",
      "Ukoronowanie NMP",
      "Zwiastowanie",
      "Nawiedzenie",
      "Narodzenie",
      "Ofiarowanie",
      "Znalezienie",
      "Chrzest w Jordanie",
      "Cud w Kanie",
      "Głoszenie Królestwa Bożego",
      "Przemienienie na górze Tabor",
      "Ustanowienie Eucharystii",
      "Modlitwa w Ogrójcu",
      "Biczowanie",
    ],
  },
  {
    person: "Nikola F.",
    weeks: [
      "Droga Krzyżowa",
      "Ukrzyżowanie i śmierć",
      "Zmartwychwstanie",
      "Wniebowstąpienie",
      "Zesłanie Ducha Świętego",
      "Wniebowzięcie NMP",
      "Ukoronowanie NMP",
      "Zwiastowanie",
      "Nawiedzenie",
      "Narodzenie",
      "Ofiarowanie",
      "Znalezienie",
      "Chrzest w Jordanie",
      "Cud w Kanie",
      "Głoszenie Królestwa Bożego",
      "Przemienienie na górze Tabor",
      "Ustanowienie Eucharystii",
      "Modlitwa w Ogrójcu",
      "Biczowanie",
      "Cierniem ukoronowanie",
    ],
  },
  {
    person: "Paweł N.",
    weeks: [
      "Ukrzyżowanie i śmierć",
      "Zmartwychwstanie",
      "Wniebowstąpienie",
      "Zesłanie Ducha Świętego",
      "Wniebowzięcie NMP",
      "Ukoronowanie NMP",
      "Zwiastowanie",
      "Nawiedzenie",
      "Narodzenie",
      "Ofiarowanie",
      "Znalezienie",
      "Chrzest w Jordanie",
      "Cud w Kanie",
      "Głoszenie Królestwa Bożego",
      "Przemienienie na górze Tabor",
      "Ustanowienie Eucharystii",
      "Modlitwa w Ogrójcu",
      "Biczowanie",
      "Cierniem ukoronowanie",
      "Droga Krzyżowa",
    ],
  },
  {
    person: "Renata G.",
    weeks: [
      "Zmartwychwstanie",
      "Wniebowstąpienie",
      "Zesłanie Ducha Świętego",
      "Wniebowzięcie NMP",
      "Ukoronowanie NMP",
      "Zwiastowanie",
      "Nawiedzenie",
      "Narodzenie",
      "Ofiarowanie",
      "Znalezienie",
      "Chrzest w Jordanie",
      "Cud w Kanie",
      "Głoszenie Królestwa Bożego",
      "Przemienienie na górze Tabor",
      "Ustanowienie Eucharystii",
      "Modlitwa w Ogrójcu",
      "Biczowanie",
      "Cierniem ukoronowanie",
      "Droga Krzyżowa",
      "Ukrzyżowanie i śmierć",
    ],
  },
  {
    person: "Tadeusz F.",
    weeks: [
      "Wniebowstąpienie",
      "Zesłanie Ducha Świętego",
      "Wniebowzięcie NMP",
      "Ukoronowanie NMP",
      "Zwiastowanie",
      "Nawiedzenie",
      "Narodzenie",
      "Ofiarowanie",
      "Znalezienie",
      "Chrzest w Jordanie",
      "Cud w Kanie",
      "Głoszenie Królestwa Bożego",
      "Przemienienie na górze Tabor",
      "Ustanowienie Eucharystii",
      "Modlitwa w Ogrójcu",
      "Biczowanie",
      "Cierniem ukoronowanie",
      "Droga Krzyżowa",
      "Ukrzyżowanie i śmierć",
      "Zmartwychwstanie",
    ],
  },
  {
    person: "Weronika N.",
    weeks: [
      "Zesłanie Ducha Świętego",
      "Wniebowzięcie NMP",
      "Ukoronowanie NMP",
      "Zwiastowanie",
      "Nawiedzenie",
      "Narodzenie",
      "Ofiarowanie",
      "Znalezienie",
      "Chrzest w Jordanie",
      "Cud w Kanie",
      "Głoszenie Królestwa Bożego",
      "Przemienienie na górze Tabor",
      "Ustanowienie Eucharystii",
      "Modlitwa w Ogrójcu",
      "Biczowanie",
      "Cierniem ukoronowanie",
      "Droga Krzyżowa",
      "Ukrzyżowanie i śmierć",
      "Zmartwychwstanie",
      "Wniebowstąpienie",
    ],
  },
  {
    person: "Zuza F.",
    weeks: [
      "Wniebowzięcie NMP",
      "Ukoronowanie NMP",
      "Zwiastowanie",
      "Nawiedzenie",
      "Narodzenie",
      "Ofiarowanie",
      "Znalezienie",
      "Chrzest w Jordanie",
      "Cud w Kanie",
      "Głoszenie Królestwa Bożego",
      "Przemienienie na górze Tabor",
      "Ustanowienie Eucharystii",
      "Modlitwa w Ogrójcu",
      "Biczowanie",
      "Cierniem ukoronowanie",
      "Droga Krzyżowa",
      "Ukrzyżowanie i śmierć",
      "Zmartwychwstanie",
      "Wniebowstąpienie",
      "Zesłanie Ducha Świętego",
    ],
  },
  {
    person: "Bogna",
    weeks: [
      "Ukoronowanie NMP",
      "Zwiastowanie",
      "Nawiedzenie",
      "Narodzenie",
      "Ofiarowanie",
      "Znalezienie",
      "Chrzest w Jordanie",
      "Cud w Kanie",
      "Głoszenie Królestwa Bożego",
      "Przemienienie na górze Tabor",
      "Ustanowienie Eucharystii",
      "Modlitwa w Ogrójcu",
      "Biczowanie",
      "Cierniem ukoronowanie",
      "Droga Krzyżowa",
      "Ukrzyżowanie i śmierć",
      "Zmartwychwstanie",
      "Wniebowstąpienie",
      "Zesłanie Ducha Świętego",
      "Wniebowzięcie NMP",
    ],
  }
];
